"""constraint on coordinates and month

Revision ID: 05f781c381cf
Revises: bc47aee29ffb
Create Date: 2024-06-02 16:03:47.902185

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = "05f781c381cf"
down_revision: Union[str, None] = "bc47aee29ffb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "_longitude_latitude_year_month_uc",
        "future_climate_data",
        ["longitude", "latitude", "year", "month"],
    )
    op.create_unique_constraint(
        "_location_id_year_month_uc",
        "past_climate_data",
        ["location_id", "year", "month"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "_location_id_year_month_uc", "past_climate_data", type_="unique"
    )
    op.drop_constraint(
        "_longitude_latitude_year_month_uc", "future_climate_data", type_="unique"
    )
    # ### end Alembic commands ###
