"""Add yield_per_unit_surface

Revision ID: 421958731695
Revises: 50c87407fcc5
Create Date: 2024-07-15 08:46:23.792262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '421958731695'
down_revision: Union[str, None] = '50c87407fcc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crop_yield_data', sa.Column('yield_per_unit_surface', sa.Float(), nullable=False, server_default="0"))
    op.drop_column('crop_yield_data', '_yield')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crop_yield_data', sa.Column('_yield', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('crop_yield_data', 'yield_per_unit_surface')
    # ### end Alembic commands ###
