"""Add soil surface

Revision ID: 50c87407fcc5
Revises: e919a4c4069e
Create Date: 2024-07-14 21:49:57.899752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '50c87407fcc5'
down_revision: Union[str, None] = 'e919a4c4069e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crop_yield_data', sa.Column('surface', sa.Float(), nullable=False, server_default="0"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('crop_yield_data', 'surface')
    # ### end Alembic commands ###
