"""Add is_visible to location

Revision ID: 6fa88a6cbdee
Revises: 9b60ae90b92d
Create Date: 2024-08-31 10:45:40.973414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '6fa88a6cbdee'
down_revision: Union[str, None] = '9b60ae90b92d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('location', sa.Column('is_visible', sa.Boolean(), server_default='false', nullable=False))
    op.drop_constraint('_longitude_latitude_uc', 'location', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_longitude_latitude_uc', 'location', ['longitude', 'latitude'])
    op.drop_column('location', 'is_visible')
    # ### end Alembic commands ###
