"""Add duration months

Revision ID: 8c6bb09dadd3
Revises: a6a1159036d5
Create Date: 2024-07-15 09:55:28.465856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '8c6bb09dadd3'
down_revision: Union[str, None] = 'a6a1159036d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crop_yield_data', sa.Column('duration_months', sa.Integer(), nullable=False, server_default="0"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('crop_yield_data', 'duration_months')
    # ### end Alembic commands ###
