"""Change yield name

Revision ID: 9213ee217063
Revises: 8c6bb09dadd3
Create Date: 2024-07-20 10:25:43.524025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '9213ee217063'
down_revision: Union[str, None] = '8c6bb09dadd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    op.alter_column("crop_yield_data", "yield_per_unit_surface", new_column_name="yield_per_hectar")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crop_yield_data', sa.Column('yield_per_unit_surface', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=False))
    op.drop_column('crop_yield_data', 'yield_per_hectar')
    # ### end Alembic commands ###
