"""Readded useless variables

Revision ID: 966f70db0d0b
Revises: 698bfb7c527a
Create Date: 2024-06-10 12:41:57.647700

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = "966f70db0d0b"
down_revision: Union[str, None] = "698bfb7c527a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "past_climate_data",
        sa.Column(
            "surface_net_solar_radiation",
            sa.Float(),
            nullable=False,
            server_default="0.0",
        ),
    )
    op.add_column(
        "past_climate_data",
        sa.Column(
            "surface_net_thermal_radiation",
            sa.Float(),
            nullable=False,
            server_default="0.0",
        ),
    )
    op.add_column(
        "past_climate_data",
        sa.Column("snowfall", sa.Float(), nullable=False, server_default="0.0"),
    )
    op.add_column(
        "past_climate_data",
        sa.Column(
            "total_cloud_cover", sa.Float(), nullable=False, server_default="0.0"
        ),
    )
    op.add_column(
        "past_climate_data",
        sa.Column(
            "dewpoint_temperature_2m", sa.Float(), nullable=False, server_default="0.0"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("past_climate_data", "dewpoint_temperature_2m")
    op.drop_column("past_climate_data", "total_cloud_cover")
    op.drop_column("past_climate_data", "snowfall")
    op.drop_column("past_climate_data", "surface_net_thermal_radiation")
    op.drop_column("past_climate_data", "surface_net_solar_radiation")
    # ### end Alembic commands ###
