"""Add is_past_climate_data_downloading

Revision ID: 9b60ae90b92d
Revises: ebad4cbf6cf2
Create Date: 2024-08-29 17:21:51.785882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '9b60ae90b92d'
down_revision: Union[str, None] = 'ebad4cbf6cf2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('location', sa.Column('is_downloading_past_climate_data', sa.Boolean(), nullable=False, server_default="false"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('location', 'is_downloading_past_climate_data')
    # ### end Alembic commands ###
