"""Removed surface

Revision ID: a6a1159036d5
Revises: 421958731695
Create Date: 2024-07-15 08:57:31.992666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'a6a1159036d5'
down_revision: Union[str, None] = '421958731695'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('crop_yield_data', 'surface')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crop_yield_data', sa.Column('surface', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
