"""Removed ph

Revision ID: bc47aee29ffb
Revises: e64cf895e126
Create Date: 2024-06-01 03:22:28.010459

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = "bc47aee29ffb"
down_revision: Union[str, None] = "e64cf895e126"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("crop_yield_data", "ph")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "crop_yield_data",
        sa.Column(
            "ph", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False
        ),
    )
    # ### end Alembic commands ###
