"""Add climate generative model table

Revision ID: d0b6299bfa2e
Revises: 8e163fdd4146
Create Date: 2024-06-08 15:48:57.044823

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = "d0b6299bfa2e"
down_revision: Union[str, None] = "8e163fdd4146"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "climate_generative_model",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("model", sa.LargeBinary(), nullable=False),
        sa.Column("x_scaler", sa.LargeBinary(), nullable=False),
        sa.Column("y_scaler", sa.LargeBinary(), nullable=False),
        sa.Column("location_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["location_id"], ["location.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("location_id", name="_location_id_nc"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("climate_generative_model")
    # ### end Alembic commands ###
