"""Remove crop id

Revision ID: d71f4b34ee85
Revises: 6fa88a6cbdee
Create Date: 2024-09-15 17:10:00.350859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'd71f4b34ee85'
down_revision: Union[str, None] = '6fa88a6cbdee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('crop_yield_data_crop_id_fkey', 'crop_yield_data', type_='foreignkey')
    op.drop_column('crop', 'id')
    op.add_column('crop_yield_data', sa.Column('crop_name', sa.String(), nullable=True, server_default=sa.text("NULL")))
    op.create_primary_key("crop_pkey", "crop", ["name"])
    op.create_foreign_key(None, 'crop_yield_data', 'crop', ['crop_name'], ['name'])
    op.drop_column('crop_yield_data', 'crop_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crop_yield_data', sa.Column('crop_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'crop_yield_data', type_='foreignkey')
    op.create_foreign_key('crop_yield_data_crop_id_fkey', 'crop_yield_data', 'crop', ['crop_id'], ['id'])
    op.drop_column('crop_yield_data', 'crop_name')
    op.add_column('crop', sa.Column('id', sa.UUID(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
