"""Removed constraint country name

Revision ID: e64cf895e126
Revises: dfd0fbd20aed
Create Date: 2024-06-01 02:57:07.689347

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = "e64cf895e126"
down_revision: Union[str, None] = "dfd0fbd20aed"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("_country_name_uc", "location", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("_country_name_uc", "location", ["country", "name"])
    # ### end Alembic commands ###
