"""Remove soil_type

Revision ID: f2738a94df5d
Revises: 58ccf6374d4d
Create Date: 2024-08-23 10:23:46.543038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'f2738a94df5d'
down_revision: Union[str, None] = '58ccf6374d4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('location_soil_type_id_fkey', 'location', type_='foreignkey')
    op.drop_column('location', 'soil_type_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('location', sa.Column('soil_type_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('location_soil_type_id_fkey', 'location', 'soil_type', ['soil_type_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
